# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최은호
title: 게임 클라이언트 프로그래머
email: eunho5751@naver.com
website: https://eunho5751.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  eunho5751
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: 이력서
    icon: fas fa-user-circle
    url: https://eunho5751.github.io/resume/

  - title: 경력기술서
    icon: fas fa-file-alt
    url: https://eunho5751.github.io/resume/career/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <font size="5"><b>반갑습니다. 최은호입니다.</b></font>
  <br>
  6년차 Unity 클라이언트 개발자로서 실감형 콘텐츠를 중심으로 개발해왔으며, 콘텐츠 개발을 지원하기 위한 다양한 시스템 개발 경험을 보유하고 있습니다.
  확장성과 유지보수성을 고려한 아키텍처 설계를 중요하게 생각하며, 변화에 유연하게 대응할 수 있는 구조를 만들기 위해 지속적으로 고민하고 노력하고 있습니다.


  새로운 경험을 하는 것을 좋아합니다. 경험을 통해 새로운 지식을 얻을 수 있고, 문제 해결 능력이 성장한다고 생각합니다.
  또한, 개인 블로그에 새롭게 얻은 경험을 정리하여 공유하고 있습니다. 머리로 알고있던 것을 글로 정리하는 과정에서 개념을 재정립하고 새로운 인사이트를 얻고 있습니다.


content:
  - title: Skill
    layout: text
    content: |
      <font size="4"><b>　Languages : C#, C++</b></font>
      - C# : Unity 개발 주력 언어로 사용해 왔으며, 콘텐츠 로직 및 시스템 구현에 능숙
      - C++ : 프로그래밍을 C++로 시작하여 언어에 대한 기본적인 이해와 Unity 플러그인 개발 경험
      <br>
      <br>
      <font size="4"><b>　Engine : Unity</b></font>
      - 엔진 기본 기능에 대한 이해 (Rigidbody, Animator, UGUI 등)
      - UniTask & CancellationToken을 통한 비동기 처리
      - DOTween을 통한 Easing 구현
      - URP RenderGraph를 통한 RenderPass 구현
      - HLSL을 통한 Vertex & Fragment Shader 작성
      - Compute Shader를 통한 병렬 처리
      - Addressables을 통한 리소스 관리
      - ScriptableObject를 통한 데이터 관리
      - HTTP, WebSocket 통신 (UnityWebRequest, Socket.IO)
      - C++ 네이티브 플러그인 연동
      - Unity Editor 확장
      <br>
      <br>
      <font size="4"><b>　Tools : Git (SourceTree/Fork), Redmine, Notion</b></font>
      <br>
      <font size="4"><b>　Etc</b></font>
      - OpenCV를 통한 영상 처리​

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 셀빅
        sub_title: 프로그램팀, 대리
        caption: 2022.12 ~ 2025.12
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4.5"><b>Unity 콘텐츠 및 시스템 다수 개발.</b></font>
            - 실감형 콘텐츠, 포토부스, 포토카드 등 다양한 콘텐츠를 전담하여 아키텍처 설계 및 구현
            - 프린터, 카드리더기 등 콘텐츠 개발에 필요한 하드웨어 연동 및 기능 모듈화
            - OpenCV 및 Shader를 활용하여 엣지블렌딩 시스템 개발
            - Localization 패키지를 확장하여 CSV 기반 로컬라이제이션 시스템 개발
            <br>
            <br>
            <font size="4.5"><b>프로젝트 유지보수 및 개선.</b></font>
            - 콘텐츠 개발에 사용되는 프레임워크 리팩토링을 통한 코드 구조 개선
            - UniTask를 활용해 코루틴 기반 비동기 로직을 async/await 기반으로 작성하여 코드 가독성 개선
            - Addressables을 통해 리소스를 관리하여 메모리 사용 및 빌드 사이즈 최적화
            <br>
            <br>
            <font size="4.5"><b>팀 내 개발 프로세스 및 개발 문화 개선.</b></font>
            - 협업 시 통일성을 유지하기 위해 네이밍 컨벤션 정립
            - 팀 내 전문성 및 협업 역량 강화를 위한 세미나 진행
            
      - layout: top-middle
        title: 셀빅
        sub_title: R&D팀, 연구원
        caption: 2019.10 ~ 2022.04
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>Unity 콘텐츠 개발에 필요한 핵심 기술 개발.</b></font>
            - 카메라 연결 및 실시간 영상 스트림을 획득하기 위한 카메라 제어 시스템 개발
            - 프로젝션 환경에서 콘텐츠와의 실시간 인터랙션을 위한 터치 검출 시스템 개발
            - OpenCV를 활용하여 이미지 내 그려진 그림을 검출·추출하는 알고리즘 개발
            <br>
            <br>
            <font size="4"><b>Unity 네이티브 플러그인 개발.</b></font>
            - 카메라 제어를 위해 카메라 SDK를 활용한 C++ 플러그인 개발      
            - 그림 이미지를 스키닝된 2D 캐릭터 생성에 필요한 데이터로 변환하는 C++ 플러그인 개발
            - 기존 C#으로 구현된 기능을 C++로 포팅하고 플러그인으로 연동하여 성능 최적화

  - title: Other Experience
    layout: list

  - title: Education
    layout: text
    content: |
        2020.03 ~ 2022.02 광운대학교스마트융합대학원 스마트시스템학과(실감콘텐츠 전공)

        2019.03 ~ 2020.02 청강문화산업대학교 만화애니게임학과(심화) - 프로그래밍
        
        2016.03 ~ 2019.02 청강문화산업대학교 게임전공 - 프로그래밍

career:
  - title: 경력기술서
    layout: list
    content:
      - layout: top-middle
        title: 셀빅
        sub_title: 프로그램팀, 대리
        caption: 2022.12 ~ 2025.12
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>판타 드로우잇｜2025.10 ~ 2025.11</b></font>
            "던파 20주년 페스티벌에 납품된 콘텐츠로, 플레이어가 그린 그림을 캐릭터화하여 맵에 배치하고 프로젝션 환경에서 손으로 터치하여 실시간 인터랙션할 수 있는 실감형 콘텐츠 개발"
            - FSM 기반 캐릭터 상태 관리 및 행동 로직 구현
            - 캐릭터 및 기믹 오브젝트의 터치·충돌 이벤트 구현
            - 키오스크에서 생성된 캐릭터 데이터 송·수신을 위한 소켓 통신 구현
            - 32:9 해상도 지원을 위해 자체 개발한 엣지블렌딩 시스템 적용
            <br>
            <br>
            <font size="4"><b>현대백화점 흰디 포토카드｜2024.09 ~ 2024.12</b></font>
            *AI 프롬프트를 조합하여 현대 백화점의 캐릭터 '흰디'를 생성형 AI로 생성하고 프린터를 이용해 포토카드로 출력하는 프로그램 개발*
            - Unity 환경에서 포토카드 출력을 위한 프린터 연동
            - 프롬프트 선택·캐릭터 생성·출력 등 전반적인 UI 기능 구현
            <br>
            <br>
            <font size="4"><b>꿈이담키즈헬스케어센터 관리자 툴｜2024.06 ~ 2024.08</b></font>
            *꿈이담키즈헬스케어센터에 납품된 콘텐츠들의 상태를 실시간으로 모니터링하고 사용자들의 정보를 관리할 수 있는 프로그램 개발*
            - 콘텐츠 상태 모니터링을 위한 웹소켓(Socket.IO) 기반 실시간 통신 구현
            - 사용자 데이터 관리를 위한 HTTP 기반 CRUD 구현
            - 모니터링 대시보드, 사용자 데이터 관리 등 전반적인 UI 기능 구현
            <br>
            <br>
            <font size="4"><b>포토하니｜2023.06 ~ 2023.12</b></font>
            *사진 촬영부터 보정·출력까지 가능한 포토부스 프로그램 개발*
            - Unity 환경에서 포토부스 개발에 필요한 하드웨어 연동 (카메라, 촬영 리모컨, 프린터, 카드단말기)
            - 얼굴 인식 기반 3D 소품 AR 합성 기능 구현
            - 결제·촬영·출력 등 전반적인 UI 기능 구현
            <br>
            <br>
            <font size="4"><b>소프트웨어 엣지블렌딩 시스템｜2023.01 ~ 2023.03</b></font>
            *멀티 프로젝션 환경에서 여러 투사 영역을 하나의 화면처럼 자연스럽게 연결하는 소프트웨어 기반 엣지블렌딩 시스템 개발*
            - OpenCV와 Shader를 활용하여 엣지블렌딩 핵심 기능 구현
            - UGUI 확장을 통해 엣지블렌딩 환경에서의 UI 인터랙션 구현
            - UI 디자인, 레이아웃, 기능 개발
            - 현장 설치 지원을 위한 사용 매뉴얼 작성
            <br>
            <br>
            <font size="4"><b>유엔젤 키즐｜2022.12 ~ 2025.07</b></font>
            *프로젝션 환경에서 손을 이용한 터치, 공 던지기와 같은 인터랙션을 통해 유아들에게 놀이 환경을 제공하는 실감형 콘텐츠 5종 개발*
            - 전반적인 콘텐츠 플레이 로직 및 연출 구현
            - 프레임워크의 유지보수성을 높이기 위해 의존성 분리 등 구조 개선
            - 팀 내 공유를 위한 프레임워크 사용 매뉴얼 작성
            
      - layout: top-middle
        title: 셀빅
        sub_title: R&D팀, 연구원
        caption: 2019.10 ~ 2022.04
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>이미지 캐릭터화 플러그인｜2020.06 ~ 2020.08</b></font>｜<mark>C#</mark>, <mark>C++</mark>, <mark>Unity</mark>, <mark>OpenCV</mark>
            *Unity 내 2D 캐릭터 생성을 위해 이미지 내 그려진 캐릭터를 검출하여 메시, 리깅, 스키닝 데이터를 생성하는 C++ 플러그인 개발*
            - OpenCV를 활용하여 캐릭터 검출 알고리즘 구현
            - 캐릭터 데이터 생성을 위해 기존 C#에서 작성된 영상처리 알고리즘을 C++로 포팅하여 성능 개선
            - Windows / Android / iOS 플랫폼별 플러그인 빌드 환경 구축
            <br>
            <br>
            <font size="4"><b>인터랙션 검출 시스템｜2020.03 ~ 2020.05</b></font>
            *실감형 콘텐츠에 사용자 인터랙션을 적용하기 위해 영상 처리 기반 인터랙션 시스템 개발*
            - 카메라 연동부터 인터랙션 검출 결과를 전달하는 전반적인 파이프라인 설계 및 구현 
            - 영상 처리 기능 모듈화를 통해 다양한 인터랙션 알고리즘을 유연하게 구현할 수 있는 구조 설계 및 구현
            - OpenCV를 활용하여 프로젝션 환경에서의 터치·움직임 검출 알고리즘 구현
            <br>
            <br>
            <font size="4"><b>카메라 제어 시스템｜2020.01 ~ 2020.02</b></font>
            *실감형 콘텐츠 개발에 사용되는 다양한 타입의 카메라를 추가 구현 없이 연동하여 실시간 영상 스트림을 획득하는 시스템 개발*
            - Unity 환경에서 카메라 제어를 위한 C++ 기반 네이티브 플러그인 개발
            - 카메라 제어 로직을 추상화하여 신규 카메라를 유연하게 확장 가능한 구조 설계
            - 카메라 연결 상태 모니터링 및 자동 재연결 기능 구현

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
