# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최은호
title: 게임 클라이언트 프로그래머
email: eunho5751@naver.com
website: https://eunho5751.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  eunho5751
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  자기소개

content:
  - title: Skills
    layout: text
    content: |
      - <b>Language</b> : C#, C++
      - <b>Engine</b> : Unity
      - <b>Framework / Library</b> : OpenCV
      - <b>Tool</b> : Git, Redmine

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 셀빅
        sub_title: 프로그램팀, 대리
        caption: 2022.12 ~ 2025.12
        description: | # this will include new lines to allow paragraphs
            <font size="4"><b>Unity를 활용하여 시스템/콘텐츠 다수 개발</b></font>
            - 인터랙티브 콘텐츠, 포토부스, 포토카드 등 다양한 콘텐츠를 전담하여 아키텍처 설계 및 구현
            - 셰이더와 영상 처리를 활용한 엣지블렌딩 시스템 개발
            - 로컬라이제이션 패키지를 확장하여 CSV 기반 로컬라이제이션 시스템 개발
            - 콘텐츠 개발에 필요한 하드웨어 SDK를 Unity와 연동하여 기능 모듈화
            
            <font size="4"><b>프로젝트 유지보수성 개선</b></font>
            - 콘텐츠 개발에 사용되는 프레임워크 리팩토링을 통한 코드 구조 개선
            - UniTask를 활용해 코루틴 기반 비동기 로직을 async/await 기반으로 작성하여 코드 가독성 개선
            - Addressables을 통해 리소스를 관리하여 메모리 사용 및 빌드 사이즈 최적화
            
            <font size="4"><b>팀 내 개발 프로세스 및 개발 문화 개선</b></font>
            - 협업 시 통일성을 유지하기 위해 네이밍 컨벤션 정립
            - 팀 내 전문성 및 협업 역량 강화를 위한 세미나 진행
            
      - layout: top-middle
        title: 셀빅
        sub_title: R&D팀, 연구원
        caption: 2019.10 ~ 2022.04
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>2D 스케치 캐릭터 생성 라이브러리｜2020.06 ~ 2020.08</b></font>
            *이미지 내 스케치된 그림을 검출하여 애니메이션이 가능한 2D 캐릭터로 변환하는 라이브러리 개발*
            - OpenCV를 활용하여 스케치 그림 검출 알고리즘 구현
            - 기존 Unity C# 스크립트로 작성된 캐릭터 생성 기능들을 성능 개선을 위해 C++로 포팅
            - Windows / Android / iOS 플랫폼별 라이브러리 빌드 환경 구축
            <br>
            <br>
            <font size="4"><b>영상 처리 기반 인터랙션 시스템｜2020.03 ~ 2020.05</b></font>
            *실감형 콘텐츠에 사용자 인터랙션을 적용하기 위해 영상 처리 기반 인터랙션 시스템 개발*
            - 카메라 연동부터 인터랙션 검출 결과를 전달하는 전반적인 파이프라인 설계 및 구현 
            - 영상 처리 기능 모듈화를 통해 다양한 인터랙션 알고리즘을 유연하게 구현할 수 있는 구조 설계 및 구현
            - OpenCV를 활용하여 프로젝션 환경에서의 터치 및 움직임 검출 알고리즘 구현
            <br>
            <br>
            <font size="4"><b>카메라 제어 시스템｜2020.01 ~ 2020.02</b></font>
            *실감형 콘텐츠 개발에 사용되는 다양한 타입의 카메라를 추가 구현 없이 연동하여 실시간 영상 스트림을 획득하는 시스템 개발*
            - Unity 환경에서 카메라 제어를 위한 C++ 기반 네이티브 플러그인 개발
            - 카메라 제어 로직을 추상화하여 신규 카메라를 유연하게 확장 가능한 구조 설계
            - 카메라 연결 상태 모니터링 및 자동 재연결 기능 구현

  - title: Other Experience
    layout: list

  - title: Education
    layout: text
    content: |
        2020.03 ~ 2022.02 광운대학교스마트융합대학원 스마트시스템학과(실감콘텐츠 전공)
        
        2016.03 ~ 2020.02 청강문화산업대학교 게임콘텐츠스쿨(프로그래밍 전공)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
