# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최은호
title: 게임 클라이언트 프로그래머
email: eunho5751@naver.com
website: https://eunho5751.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  eunho5751
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: 이력서
    icon: fas fa-user-circle
    url: https://eunho5751.github.io/resume/

  - title: 경력기술서
    icon: fas fa-file-alt
    url: https://eunho5751.github.io/resume/career/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <font size="5"><b>반갑습니다. 최은호입니다.</b></font>
  <br>
  6년차 Unity 클라이언트 개발자로서 실감형 콘텐츠를 중심으로 개발해왔으며, 콘텐츠 개발을 지원하기 위한 다양한 시스템 개발 경험을 보유하고 있습니다.
  확장성과 유지보수성을 고려한 아키텍처 설계를 중요하게 생각하며, 변화에 유연하게 대응할 수 있는 구조를 만들기 위해 지속적으로 고민하고 노력하고 있습니다.


  새로운 경험을 하는 것을 좋아합니다. 경험을 통해 새로운 지식을 얻을 수 있고, 문제 해결 능력이 성장한다고 생각합니다.
  또한, 개인 블로그에 새롭게 얻은 경험을 정리하여 공유하고 있습니다. 머리로 알고있던 것을 글로 정리하는 과정에서 개념을 재정립하고 새로운 인사이트를 얻고 있습니다.


content:
  - title: Skill
    layout: text
    content: |
      <font size="4"><b>　Languages : C#, C++</b></font>
      - C# : Unity 개발 주력 언어로 사용해 왔으며, 콘텐츠 로직 및 시스템 구현에 능숙
      - C++ : 프로그래밍을 C++로 시작하여 언어에 대한 기본적인 이해와 Unity 플러그인 개발 경험
      <br>
      <br>
      <font size="4"><b>　Engine : Unity</b></font>
      - 엔진 기본 기능에 대한 이해 (Rigidbody, Animator, UGUI 등)
      - Unity Editor 확장 ( Inspector, Window Customization )
      - UniTask & CancellationToken을 통한 비동기 처리
      - DOTween을 통한 Easing 구현
      - URP RenderGraph를 통한 RenderPass 구현
      - HLSL을 통한 Vertex, Fragment Shader 작성
      - Compute Shader를 통한 병렬 처리
      - Addressables을 통한 리소스 관리
      - ScriptableObject를 통한 데이터 관리
      - HTTP, WebSocket 통신 (UnityWebRequest, Socket.IO)
      - C++ 네이티브 플러그인 연동
      <br>
      <br>
      <font size="4"><b>　Tools : Git (SourceTree/Fork), Redmine, Notion</b></font>
      <br>
      <font size="4"><b>　Etc</b></font>
      - OpenCV를 통한 영상 처리​

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 셀빅
        sub_title: 프로그램팀, 대리
        caption: 2022.12 ~ 2025.12
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4.5"><b>Unity 콘텐츠 및 시스템 다수 개발.</b></font>
            - 실감형 콘텐츠, 포토부스, 포토카드 등 다양한 콘텐츠를 전담하여 아키텍처 설계 및 구현
            - 고해상도 콘텐츠 개발을 위해 OpenCV와 Shader를 활용한 엣지블렌딩 시스템 개발
            - Localization 패키지를 확장하여 CSV 기반 로컬라이제이션 시스템 개발
            - 프린터, 카드리더기 등 콘텐츠 개발에 필요한 하드웨어 연동 및 기능 모듈화
            <br>
            <br>
            <font size="4.5"><b>프로젝트 유지보수 및 개선.</b></font>
            - 콘텐츠 개발에 사용되는 프레임워크 리팩토링을 통한 코드 구조 개선
            - UniTask를 통해 Coroutine을 async/await 기반으로 작성하여 비동기 코드 구조 개선
            - Addressables을 활용한 리소스 관리를 통해 메모리 사용 및 빌드 사이즈 최적화
            <br>
            <br>
            <font size="4.5"><b>팀 내 개발 프로세스 및 개발 문화 개선.</b></font>
            - 협업 시 통일성을 유지하기 위해 네이밍 컨벤션 정립
            - 팀 내 전문성 및 협업 역량 강화를 위한 세미나 진행
            <br>
            <br>
            
      - layout: top-middle
        title: 셀빅
        sub_title: R&D팀, 연구원
        caption: 2019.10 ~ 2022.04
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>Unity 콘텐츠 개발에 필요한 핵심 기술 개발.</b></font>
            - 다양한 종류의 카메라 연결 및 실시간 영상 스트림 획득을 위한 카메라 제어 시스템 개발
            - 프로젝션 환경에서의 실시간 인터랙션을 위한 영상처리 기반 인터랙션 검출 시스템 개발
            - 영상처리를 통해 이미지 내 캐릭터 그림 검출 알고리즘 개발
            <br>
            <br>
            <font size="4"><b>Unity 네이티브 플러그인 개발.</b></font>
            - 카메라 제어를 위해 카메라 SDK를 활용한 C++ 플러그인 개발
            - 이미지 내 그림을 검출하여 2D 캐릭터화를 위한 영상처리 기반 메시·리깅·스키닝 데이터 생성 C++ 플러그인 개발

  - title: Other Experience
    layout: list

  - title: Education
    layout: text
    content: |
        2020.03 ~ 2022.02 광운대학교스마트융합대학원 스마트시스템학과(실감콘텐츠 전공)

        2019.03 ~ 2020.02 청강문화산업대학교 만화애니게임학과(심화) - 프로그래밍
        
        2016.03 ~ 2019.02 청강문화산업대학교 게임전공 - 프로그래밍

career:
  - title: 경력기술서
    layout: list
    content:
      - layout: top-middle
        title: 셀빅
        sub_title: 프로그램팀, 대리
        caption: 2022.12 ~ 2025.12
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>[던파 20주년 페스티벌] 판타 드로우잇｜2025.10 ~ 2025.11</b></font>
            *그림을 캐릭터화하여 맵에 배치하고 프로젝션 환경에서 손으로 터치하여 실시간 인터랙션할 수 있는 실감형 콘텐츠 개발*
            - FSM 기반 캐릭터·기믹 오브젝트 상태 관리 및 로직 구현
            - Object Pool 패턴을 적용해 터치 이펙트 등 오브젝트를 재사용하여 프레임 드랍 최소화
            - 키오스크에서 생성된 캐릭터 데이터 송·수신을 위한 소켓 통신 구현
            - 32:9 해상도 지원을 위해 자체 개발한 엣지블렌딩 시스템 적용

            <mark>C#</mark> <mark>Unity</mark>
            <br>
            <br>
            <font size="4"><b>[더현대 서울] 흰디 포토카드｜2024.09 ~ 2024.12</b></font>
            *AI 프롬프트를 조합하여 현대 백화점의 캐릭터 '흰디'를 생성형 AI로 생성하고 포토카드 프린터를 통해 출력하는 포토카드 소프트웨어 개발*
            - 프롬프트 선택·캐릭터 생성·출력 등 UI 기능 구현 (UGUI)
            - ScriptableObject 기반 프롬프트 관리를 통해 데이터와 로직을 분리하여 유지보수성 개선
            - 포토카드 프린터 연동 및 기능 모듈화

            <mark>C#</mark> <mark>Unity</mark>
            <br>
            <br>
            <font size="4"><b>[꿈이담키즈헬스케어센터] 관리자 툴｜2024.06 ~ 2024.08</b></font>
            *꿈이담키즈헬스케어센터에 납품된 콘텐츠들의 상태를 실시간으로 모니터링하고 고객들의 정보를 관리하는 소프트웨어 개발*
            - 모니터링 대시보드, 고객 관리 등 UI 기능 구현 (UGUI)
            - 콘텐츠 상태 모니터링을 위한 WebSocket 기반 실시간 통신 구현 (Socket.IO)
            - 고객 데이터 관리를 위한 HTTP 기반 CRUD 구현 (UnityWebRequest)

            <mark>C#</mark> <mark>Unity</mark>
            <br>
            <br>
            <font size="4"><b>포토하니｜2023.06 ~ 2023.12</b></font>
            *카메라를 통해 인물 사진을 촬영하고 보정하여 포토 프린터를 통해 출력하는 포토부스 소프트웨어 개발*
            - 결제·촬영·출력 등 UI 기능 구현 (UGUI)
            - 카드 결제를 위한 서드파티 결제 솔루션 연동 (KSNET)
            - 3D 소품을 실시간으로 얼굴에 합성하는 AR 기능 구현
            - 촬영 및 출력을 위한 하드웨어 연동 및 기능 모듈화 (카메라, 촬영 리모컨, 프린터)

            <mark>C#</mark> <mark>Unity</mark>
            <br>
            <br>
            <font size="4"><b>엣지블렌딩 시스템｜2023.01 ~ 2023.03</b></font>
            *멀티 프로젝션 환경에서 여러 투사 영역을 하나의 화면처럼 자연스럽게 연결하는 소프트웨어 기반 엣지블렌딩 시스템 개발*
            - OpenCV와 Shader를 활용하여 엣지블렌딩 핵심 기능 구현 (Warping, Blending)
            - UGUI 확장을 통해 엣지블렌딩(고해상도) 환경에서의 UI 인터랙션 기능 구현
            - UI 디자인, 레이아웃, 기능 개발 (UGUI)

            <mark>C#</mark> <mark>Unity</mark> <mark>OpenCV</mark>
            <br>
            <br>
            
      - layout: top-middle
        title: 셀빅
        sub_title: R&D팀, 연구원
        caption: 2019.10 ~ 2022.04
        description: | # this will include new lines to allow paragraphs
            <br>
            <font size="4"><b>LiveCharacter Plugin｜2020.06 ~ 2020.08</b></font>
            *이미지 내 그림을 검출하여 2D 캐릭터화를 위한 영상처리 기반 메시·리깅·스키닝 데이터 생성 C++ 플러그인 개발*
            - OpenCV를 활용하여 캐릭터 그림 검출 알고리즘 개발
            - 기존 C# 기반 캐릭터 생성 관련 영상처리 알고리즘을 C++로 포팅하여 성능 개선
            - Windows / Android / iOS 플랫폼별 플러그인 빌드 환경 구축

            <mark>C#</mark> <mark>C++</mark> <mark>Unity</mark> <mark>OpenCV</mark>
            <br>
            <br>
            <font size="4"><b>Detection System｜2020.03 ~ 2020.05</b></font>
            *프로젝션 환경에서의 실시간 인터랙션을 위한 영상처리 기반 인터랙션 검출 시스템 개발*
            - 카메라 연동부터 인터랙션 검출 결과를 전달하는 전반적인 파이프라인 설계 및 구현
            - 멀티스레딩을 통해 인터랙션 검출과 결과의 처리를 분리하여 성능 병목 최소화
            - OpenCV를 활용하여 터치·움직임 검출 알고리즘 구현

            <mark>C#</mark> <mark>Unity</mark> <mark>OpenCV</mark>
            <br>
            <br>
            <font size="4"><b>VideoDevice System｜2020.01 ~ 2020.02</b></font>
            *웹캠, 키넥트 등 다양한 종류의 카메라 연결 및 실시간 영상 스트림 획득을 위한 카메라 제어 시스템 개발*
            - Unity 환경에서 카메라 제어를 위해 카메라 SDK를 활용한 C++ 플러그인 개발
            - 카메라 제어 로직을 추상화하여 인터페이스를 통해 신규 카메라를 유연하게 확장 가능한 구조 설계
            - 카메라 연결 상태 모니터링 및 자동 재연결 기능 구현

            <mark>C#</mark> <mark>C++</mark> <mark>Unity</mark> <mark>OpenCV</mark>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
